//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBallTeamApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameDay
    {
        public int GameNo { get; set; }
        public string Date { get; set; }
        public string Time { get; set; }
        public string Venue { get; set; }
        public string PaidBy { get; set; }
        public Nullable<decimal> PaidAmount { get; set; }
        public Nullable<int> PassedGame { get; set; }
    
        public virtual Player Player { get; set; }
    }
}
